import type { RubricItem } from '../../shared/rubric.ts'
import { createPluginsContextFactory, type PluginsContext } from '../contexts/plugins.ts'
import { KI_PLUGINS_RUBRIC } from './catalogue.ts'

type NativePluginsContext = Omit<
  PluginsContext,
  'dryRun' | 'conformMarketplaceOwner' | 'conformJsonFormatting' | 'conformPluginAgreement'
> & {
  readonly repository: string
}

type LegacyFamily = {
  readonly code: string
  readonly title: string
  readonly items: readonly RubricItem<PluginsContext>[]
}

const catalogueDefinition = KI_PLUGINS_RUBRIC
const catalogue = catalogueDefinition.families as unknown as readonly LegacyFamily[]

const mechanical = (item: RubricItem<PluginsContext>) => {
  const definition = item.mechanical
  if (!definition) throw new Error(`${item.code} must be mechanical`)
  return {
    kind: 'mechanical' as const,
    code: item.code,
    title: item.title,
    level: definition.level,
    phase: definition.audit.phase,
    audit: (context: NativePluginsContext) => definition.audit.run(context as unknown as PluginsContext)
  }
}

const judgment = (item: RubricItem<PluginsContext>) => {
  const definition = item.judgment
  if (!definition) throw new Error(`${item.code} must be a judgment item`)
  return { kind: 'judgment' as const, code: item.code, title: item.title, prompt: definition.prompt }
}

const nativeItem = (item: RubricItem<PluginsContext>) => (item.mechanical ? mechanical(item) : judgment(item))

// Marketplace manifests and the projected plugin are generated by ki-binding.
// Even apparently local JSON fixes would create a hand-maintained projection,
// so the native host reports them and leaves regeneration an explicit action.

type NativeRuntimeItem = {
  readonly kind: 'mechanical' | 'judgment'
  readonly phase?: 'PREPARE' | 'INSPECT' | 'PRIMARY' | 'DERIVED' | 'NORMALISE'
  readonly audit?: (...arguments_: never[]) => unknown
  readonly repair?: (...arguments_: never[]) => unknown
}

const directItem = <Context>(item: RubricItem<Context>, runtime: NativeRuntimeItem) => {
  if (!item.mechanical) return item
  if (runtime.kind !== 'mechanical' || !runtime.phase || !runtime.audit) throw new Error(`${item.code} has no native mechanical runtime`)
  const { repair: legacyRepair, ...mechanical } = item.mechanical
  void legacyRepair
  return {
    ...item,
    mechanical: {
      ...mechanical,
      audit: { phase: runtime.phase, run: runtime.audit },
      ...(runtime.repair ? { repair: { phase: 'NORMALISE', run: runtime.repair } } : {})
    }
  }
}

export default {
  contract: 1,
  name: 'ki-plugins',
  concern: catalogueDefinition.concern,
  createContext: ({ repository }: { readonly repository: string }): NativePluginsContext => {
    const {
      dryRun: _dryRun,
      conformMarketplaceOwner: _conformMarketplaceOwner,
      conformJsonFormatting: _conformJsonFormatting,
      conformPluginAgreement: _conformPluginAgreement,
      ...evidence
    } = createPluginsContextFactory({ target: repository, dryRun: true })()
    return { repository, ...evidence }
  },
  families: catalogue.map((family) => ({
    ...family,
    selectContext: (context: unknown) => context,
    items: family.items.map((item) => directItem(item, nativeItem(item)))
  }))
} as const

export * from './catalogue.ts'
