import type { RubricItem } from '../vendored/ki-skills/rubric.ts'
import { createPluginsContextFactory, type PluginsContext } from './contexts/plugins.ts'
import { KI_PLUGINS_RUBRIC } from './items/index.ts'

type NativePluginsContext = Omit<
  PluginsContext,
  'dryRun' | 'conformMarketplaceOwner' | 'conformJsonFormatting' | 'conformPluginAgreement'
> & {
  readonly repository: string
}

type LegacyFamily = {
  readonly code: string
  readonly title: string
  readonly items: readonly RubricItem<PluginsContext>[]
}

const catalogue = KI_PLUGINS_RUBRIC.families as unknown as readonly LegacyFamily[]

const mechanical = (item: RubricItem<PluginsContext>) => {
  const definition = item.mechanical
  if (!definition) throw new Error(`${item.code} must be mechanical`)
  return {
    kind: 'mechanical' as const,
    code: item.code,
    title: item.title,
    level: definition.level,
    phase: definition.audit.phase,
    audit: (context: NativePluginsContext) => definition.audit.run(context as unknown as PluginsContext)
  }
}

const judgment = (item: RubricItem<PluginsContext>) => {
  const definition = item.judgment
  if (!definition) throw new Error(`${item.code} must be a judgment item`)
  return { kind: 'judgment' as const, code: item.code, title: item.title, prompt: definition.prompt }
}

const nativeItem = (item: RubricItem<PluginsContext>) => (item.mechanical ? mechanical(item) : judgment(item))

// Marketplace manifests and the projected plugin are generated by ki-binding.
// Even apparently local JSON fixes would create a hand-maintained projection,
// so the native host reports them and leaves regeneration an explicit action.
export default {
  contract: 1,
  skill: 'ki-plugins',
  createContext: ({ repository }: { readonly repository: string }): NativePluginsContext => {
    const {
      dryRun: _dryRun,
      conformMarketplaceOwner: _conformMarketplaceOwner,
      conformJsonFormatting: _conformJsonFormatting,
      conformPluginAgreement: _conformPluginAgreement,
      ...evidence
    } = createPluginsContextFactory({ target: repository, dryRun: true })()
    return { repository, ...evidence }
  },
  families: catalogue.map((family) => ({
    code: family.code,
    title: family.title,
    items: family.items.map(nativeItem)
  }))
} as const
